# Generated by Django 4.0.6 on 2022-07-21 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=20, unique=True)),
                ('crt', models.BinaryField()),
                ('update_date', models.DateTimeField(default=datetime.datetime(2022, 7, 21, 18, 38, 35, 836008))),
            ],
        ),
    ]
