# Generated by Django 4.0.6 on 2022-07-21 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='crt',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 18, 43, 36, 596371)),
        ),
    ]
