# Generated by Django 4.0.6 on 2022-07-21 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_core', '0002_alter_frame_crt_alter_frame_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='crt',
            new_name='file_bin',
        ),
        migrations.AlterField(
            model_name='frame',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 18, 44, 44, 473681)),
        ),
    ]
